language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
before_install:
  - pip install coverage
install:
  - pip install .
script:
  - PYTHONPATH=. python -m unittest -v tests
after_success:
  - coverage rum -m discover
sudo: false
